modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="fectaria"
version="1.0.0"
displayName="Fectarian Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="KalIDitzy, SwigityOS, MCreator"
description="For private use in Fectarian servers."

[[dependencies.fectaria]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




